config/routes.rb
Rails.application.routes.draw do
  
  
  resources :semesters
  resources :matters
  resources :metters
  resources :programs
  resources :faculties
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'welcome#index'
  get 'welcome/calificar'

=begin 
=end

end

app/models/metter.rb
class Metter < ActiveRecord::Base
  belongs_to :program
  
  has_many :has_matter
  has_many :users, through: :has_matter
  
  after_create :save_users
  
  def users=(value)
    @users = value
  end
  
  private
  
  def save_users
        
        unless @users.nil?
            
            @users.each do |user_id|
                HasMatter.create(user_id: user_id,metter_id: self.id) #self es una instancia de article, es decir una instancia de article
            end 
        end 
  end
  
end

app/controllers/metters_controller.rb
class MettersController < ApplicationController
  before_action :set_metter, only: [:show, :edit, :update, :destroy]

  def calificar
  end
  # GET /metters
  # GET /metters.json
  def index
    @metters = Metter.all
  end

  # GET /metters/1
  # GET /metters/1.json
  def show
    @users = User.where("permission_level = 'Estudiante'")
  end

  # GET /metters/new
  def new
    @metter = Metter.new
    @users = User.new
    @users = User.where("permission_level = 'Estudiante'")
    @usersT = User.where("permission_level = 'Profesor'")
    
   # 
  end

  # GET /metters/1/edit
  def edit
     @users = User.where("permission_level = 'Estudiante'")
     @usersT = User.where("permission_level = 'Profesor'")
  end

  # POST /metters
  # POST /metters.json
  def create
    @metter = Metter.new(metter_params)
    @metter.users = params[:users]
    

    respond_to do |format|
      if @metter.save
        format.html { redirect_to @metter, notice: 'Metter was successfully created.' }
        format.json { render :show, status: :created, location: @metter }
      else
        format.html { render :new }
        format.json { render json: @metter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /metters/1
  # PATCH/PUT /metters/1.json
  def update
    respond_to do |format|
      if @metter.update(metter_params)
        format.html { redirect_to @metter, notice: 'Metter was successfully updated.' }
        format.json { render :show, status: :ok, location: @metter }
      else
        format.html { render :edit }
        format.json { render json: @metter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /metters/1
  # DELETE /metters/1.json
  def destroy
    @metter.destroy
    respond_to do |format|
      format.html { redirect_to metters_url, notice: 'Metter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_metter
      @metter = Metter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def metter_params
      params.require(:metter).permit(:name, :program_id, :users)
    end
end

app/helpers/metters_helper.rb
module MettersHelper
end

app/views/metters/_form.html.erb
<%= form_for(@metter) do |f| %>
  <% if @metter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@metter.errors.count, "error") %> prohibited this metter from being saved:</h2>

      <ul>
      <% @metter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :program_id %><br>
    <%= f.select :program_id, Program.all.collect {|x| [x.name, x.id]}, {}, :multiple => false %>
  </div>
  <% if current_user.permission_level == "Profesor" or current_user.permission_level == "Administrador" %>
    <label>Estudiantes</label>
    <% @users.each do |user_id| %>
    <div class="field">
      <%= check_box_tag "users[]", user_id.id%> <%= user_id.name%> <%= user_id.last_name%>
    </div>
    <%end%>
  <%end%>
  
  <% if current_user.permission_level == "Administrador" %>
    <label>Profesor</label>
    <% @usersT.each do |user_id| %>
    <div class="field">
      <%= check_box_tag "users[]", user_id.id%> <%= user_id.name%> <%= user_id.last_name%>
    </div>
    <%end%>
  <%end%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/metters/edit.html.erb
<h1>Editando la Materia</h1>

<%= render 'form' %>

<%= link_to 'Show', @metter %> |
<%= link_to 'Back', metters_path %>

app/views/metters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Metters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Program</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @metters.each do |metter| %>
      <tr>
        <td><%= metter.name %></td>
        <td><%= metter.program.name %></td>
        <td><%= link_to 'Show', metter %></td>
        <td><%= link_to 'Edit', edit_metter_path(metter) %></td>
        <td><%= link_to 'Destroy', metter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Metter', new_metter_path %>

app/views/metters/new.html.erb
<h1>Nueva Materia</h1>

<%= render 'form' %>

<%= link_to 'Back', metters_path %>

app/views/metters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @metter.name %>
</p>

<p>
  <strong>Program:</strong>
  <%= @metter.program.name %>
</p>
<p>
  <strong>Estudiantes Inscritos</strong>
  <% @metter.users.where(permission_level: "Estudiante").find_each do |user|%>
  <div class="field">
     <label>
       Nombres: 
     </label> <%= user.name%> <%= user.last_name%>
     </div>
  
  <%end%>
</p>

<p>
  <strong>Profesor de la materia escrito</strong>
 <% @metter.users.where(permission_level: "Profesor").find_each do |user|%>
  <div class="field">
     <label>
       Nombres: 
     </label> <%= user.name%> <%= user.last_name%>
     </div>
  
  <%end%>
  
</p>
<%= link_to 'Edit', edit_metter_path(@metter) %> |
<%= link_to 'Back', metters_path %>