config/routes.rb
Rails.application.routes.draw do
  
  
  resources :semesters
  resources :matters
  resources :metters
  resources :programs
  resources :faculties
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'welcome#index'
  get 'welcome/calificar'

=begin 
=end

end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
    
     has_many :programs
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  before_action :set_faculty, only: [:show, :edit, :update, :destroy]

  # GET /faculties
  # GET /faculties.json
  def index
    @faculties = Faculty.all
  end

  # GET /faculties/1
  # GET /faculties/1.json
  def show
  end

  # GET /faculties/new
  def new
    @faculty = Faculty.new
  end

  # GET /faculties/1/edit
  def edit
  end

  # POST /faculties
  # POST /faculties.json
  def create
    @faculty = Faculty.new(faculty_params)

    respond_to do |format|
      if @faculty.save
        format.html { redirect_to @faculty, notice: 'Faculty was successfully created.' }
        format.json { render :show, status: :created, location: @faculty }
      else
        format.html { render :new }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faculties/1
  # PATCH/PUT /faculties/1.json
  def update
    respond_to do |format|
      if @faculty.update(faculty_params)
        format.html { redirect_to @faculty, notice: 'Faculty was successfully updated.' }
        format.json { render :show, status: :ok, location: @faculty }
      else
        format.html { render :edit }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faculties/1
  # DELETE /faculties/1.json
  def destroy
    @faculty.destroy
    respond_to do |format|
      format.html { redirect_to faculties_url, notice: 'Faculty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faculty
      @faculty = Faculty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faculty_params
      params.require(:faculty).permit(:name)
    end
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/views/faculties/_form.html.erb
<%= form_for(@faculty) do |f| %>
  <% if @faculty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@faculty.errors.count, "error") %> prohibited this faculty from being saved:</h2>

      <ul>
      <% @faculty.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Nombre Facultad" %><br>
    <%= f.text_field :name,class: "form-control"%>
  </div>
  <div class="actions">
    <%= f.submit "Crear Facultad",class:"btn be-green white"%>
  </div>
<% end %>

app/views/faculties/edit.html.erb
<h1>Editing Faculty</h1>

<%= render 'form' %>

<%= link_to 'Show', @faculty %> |
<%= link_to 'Back', faculties_path %>

app/views/faculties/index.html.erb
<p id="notice"><%= notice %></p>

<div class="top-space center-xs">
  
      <h1>Lista de Facultades</h1>
    <% @faculties.each do |faculty| %>
    <div class="row center-xs">
     
      <div class="col-xs-1 col-md-1">
        
        <%= faculty.name %>
      </div>
      <div class="col-xs-1 col-md-1">
        <%= link_to 'Detalles', faculty %>
      </div class="col-xs-1 col-md-1">
        <%= link_to 'Editar', edit_faculty_path(faculty) %>
      <div>
        <div class="col-xs-1 col-md-1">
          <%= link_to 'Eliminar', faculty, method: :delete, data: { confirm: 'Seguro que desea borrar?' },class:"red" %>
        </div>
      </div>
    </div>
     <% end %>
</div>
<div class="top-space blue">
   <%= link_to 'Agregar Facultad', new_faculty_path %>
</div>

app/views/faculties/new.html.erb
<div class="row center-xs">
  <div class="col-xs-8 col-md-6">
    <div class="box text-left">
        <h1>Nueva Facultad</h1>

            <%= render 'form' %>
            
            <%= link_to 'Lista de Facultades', faculties_path %>

        </div>
    </div>
</div>

app/views/faculties/show.html.erb
<p id="notice"><%= notice %></p>

<div class="top-space center-xs">
    <p>
    <strong>Nombre:</strong>
    <%= @faculty.name %>
  </p>
  
  <%= link_to 'Editar', edit_faculty_path(@faculty),class:"underline" %> |
  <%= link_to 'Atras', faculties_path,class:"underline" %>
</div>